stow /home/ehrenschwan/dotfiles/alacritty
stow /home/ehrenschwan/dotfiles/nvim
stow /home/ehrenschwan/dotfiles/lazygit
stow /home/ehrenschwan/dotfiles/qtile
stow /home/ehrenschwan/dotfiles/starship
stow /home/ehrenschwan/dotfiles/tmux
stow /home/ehrenschwan/dotfiles/xinit
stow /home/ehrenschwan/dotfiles/Xresources
stow /home/ehrenschwan/dotfiles/zsh
