-- My NVIM config
require('settings')
require('mapping.maps')
require('plugins')
require('lsp-config.language-servers')
require('plugins.treesitter')
require('plugins.colorscheme')
require('plugins.cmp')
require('plugins.null-ls')
require('plugins.luasnip')
